2 cbh scoring system
TeamSnowballSlam/Snowball-Slam-World-Tour pull request #26
Opened 2024-05-01 07:03 UTC by ChaseBENNC9

## Describe your changes

Add description here

## Issue number and link

#(Issue number this is fixing)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-05-02 04:36 UTC, PBWiseman requested changes
# Code Review

## Functional Requirements
_Is the application fit for purpose? Does it meet the user’s requirements and properly address the issue?_  

 - Feature looks good! Everything works well.


## Legibility and Style
_Uses agreed coding standards/conventions? Readable, consistent and well-structured with useful comments?_  

 - My only concern is that it might be better practice to use a game state enum instead of the round over and round started bool? Would there be issues with that? It could also incorporate a paused state and it would mean that you could just check if the game is in the active enum rather than checking if each different bool is set correctly? Also the variable could go in GameSettings so be better scoped for something that will be likely used by a lot of different files.

## Implementation
_Any notable performance/speed issues? Compatibility and Responsiveness on other platforms ?_  

 - None


# Final Comments

 - Would like to hear your thoughts about the enum idea. Other than that and a couple of minor formatting issues I am happy for this to be merged.

***

2024-05-02 04:36 UTC, PBWiseman commented on Assets/Scripts/LevelManager.cs
> +        {
Extra bracket here.

2024-05-02 04:36 UTC, PBWiseman commented on Assets/Scripts/LevelManager.cs
> +        if (team == Teams.Penguins)
Would this be better as a switch statement?

2024-05-02 04:39 UTC, PBWiseman commented
Another issue I just found is that sometime the score still updates after 15 is reached if the snowball is in the air at the time.
![image](https://github.com/TeamSnowballSlam/Snowball-Slam-World-Tour/assets/104882337/c39e84a0-99ed-49d1-8da5-da8b0dfb7ae2)
There were many more than 2 in the air but only the first couple counted and then it stopped counting.

2024-05-03 00:43 UTC, ChaseBENNC9 commented
That should cover both the issues.

The enum has been implemented and I believe it should be functioning as expected. 

The score should no longer go above 15 or essentially whatever the target score is set to.

I haven't yet had a look at the enemy movement issue but will get to that.

2024-05-05 02:07 UTC, PBWiseman approved these changes
Concerns addressed. Happy for this to be merged

2024-05-06 04:34 UTC, erokasyuart requested changes
Looks pretty good otherwise!

2024-05-06 04:34 UTC, erokasyuart commented on Assets/Scripts/LevelManager.cs
> +                    // if (!roundStarted)
Commented code needed?

2024-05-06 04:34 UTC, erokasyuart commented on Assets/Scripts/LevelManager.cs
> +    private string GetTeamName(Teams team)
I have to agree, this would be a good place for a switch!

2024-05-06 04:34 UTC, erokasyuart commented on Assets/Scripts/LevelManager.cs
> +    private void DisplayWinner(string winner)
Same with this! I can see this as a switch too.

2024-05-06 04:43 UTC, erokasyuart approved these changes
Looks good.

2024-05-06 05:07 UTC, merged