End Game System
TeamSnowballSlam/Snowball-Slam-World-Tour pull request #31
Opened 2024-05-02 00:45 UTC by ChaseBENNC9

## Describe your changes

Continuing from the scoring system, this branch will add in an end game. depending on the winner the teams will appear at different positions in the level, 
- once ready the branch can implement the cheering animations 
- will have a button to restart or continue to level select

## Issue number and link

#30 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-05-03 00:45 UTC, ChaseBENNC9 commented
This should be ready to review now. When you either run out of time or get to the score. The end game will show and the placeholder models will appear either in the front or back depending who won.

If it's a tie all of them will appear at the same line

2024-05-06 04:37 UTC, erokasyuart requested changes
Are you still planning on having a restart and continue button?

2024-05-06 04:42 UTC, ChaseBENNC9 commented
> Are you still planning on having a restart and continue button?

Could be quickly done after merge as I have no scene to load in my branch currently

2024-05-06 23:39 UTC, erokasyuart approved these changes

2024-05-07 00:22 UTC, merged