3 cbh joey
TeamSnowballSlam/Snowball-Slam-World-Tour pull request #40
Opened 2024-05-07 02:58 UTC by ChaseBENNC9

Click the `Preview` tab and select a Pull Request template:

- [Basic Template](?quick_pull=1&template=basic_template.md)
- [Major Version](https://github.com/TeamSnowballSlam/Snowball-Slam-World-Tour/compare/main...staging?quick_pull=1&labels=major+update&title=Change+Title+V1.x.0&template=major_version.md)

2024-05-12 02:33 UTC, ChaseBENNC9 commented
Ready to Review
Scene is setup in JoeyTurret
Each enemy has a x% chance of placing a turret and the end of their path. you can modify the chance with the slider in the inspector.
Joey will last for a set ammount of time, at this moment its 15 seconds after which it will be destroyed
the joey firing rate is supposed to be faster but it might need to change to feel right
for joey turning i have two options.
a) It fires at the set angles like the main enemy 
b) it will constantly track and face towards the closest player.

to see each option there is a commented out line 
`if (CheckForPlayerDirection() != Vector3.zero) //If the player is in a direction`
found at `JoeyTurret.cs` line 33
that can be used to switch between them. that line will make it only use set directions (a) or if commented out (b) will be used. 

I've also just fixed the bug where friendly fire can happen as i needed a fix in this branch anyway

2024-05-12 04:54 UTC, PBWiseman requested changes
# Code Review

## Functional Requirements
_Is the application fit for purpose? Does it meet the user’s requirements and properly address the issue?_  

 - Good feature. Placement and shooting work well.

## Correctness of the Code
_Is the code reliable, giving same results every time it runs? Does it function correctly?_  

 - The Joeys can sometimes spawn inside and beyond the walls of the play arena. Obviously these walls are temporary but there will be both outer bounds that we don't want them spawning in as well as walls within the play space
![image](https://github.com/TeamSnowballSlam/Snowball-Slam-World-Tour/assets/104882337/a36c79d9-e09d-49f1-81dd-b346e546a910)

- The Joey currently has no collision. Do we want there to be collision?

- All Kangaroos other than the first one currently have the turret placing script disabled and the % chance set to zero. I assume this was intentional for testing but don't forget to change that (and remove the debug.log) before merging.

# Final Comments

 - Happy for this to be merged when bugs addressed!

***

2024-05-12 07:03 UTC, erokasyuart requested changes
# Code Review

## Functional Requirements
_Is the application fit for purpose? Does it meet the user’s requirements and properly address the issue?_  

 - Yes, Joeys spawn and shoot.


## Legibility and Style
_Uses agreed coding standards/conventions? Readable, consistent and well-structured with useful comments?_  

 - (EnterTextHere)

_Any repetitive code that could be refactored? (DRY)_  

 - No issue


## Correctness of the Code
_Is the code reliable, giving same results every time it runs? Does it function correctly?_  

 - Good


## Implementation
_Any notable performance/speed issues? Compatibility and Responsiveness on other platforms ?_  

 - No


# Final Comments

 - The joey turret continues to shoot during the game end screen
***

2024-05-12 07:03 UTC, erokasyuart commented on Assets/Scripts/KangarooAbility.cs
> +        Debug.Log("canUSeTurret: "  + canUseTurret);
Make sure this gets removed

2024-05-12 22:37 UTC, PBWiseman commented
Issues addressed!

2024-05-12 22:37 UTC, PBWiseman approved these changes

2024-05-13 22:52 UTC, erokasyuart approved these changes

2024-05-13 23:26 UTC, merged