Enemy Pathfinding
TeamSnowballSlam/Snowball-Slam-World-Tour pull request #6
Opened 2024-04-09 07:44 UTC by ChaseBENNC9

## Describe your changes

Enemy Pathfinding, Movement, player detection

# Issue

#2 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-04-10 22:28 UTC, ChaseBENNC9 commented
https://docs.unity3d.com/ScriptReference/AI.NavMeshAgent.html

2024-04-14 00:47 UTC, ChaseBENNC9 commented
Ready for testing, the enemy should wander around the plane randomly. Currently the player detection is not working so its just the movement for now, I wan't to change the movement to be smoother but would like some feedback to see how it feels at the moment Ideally when the player detection is added the enemy would move to a position and check for any players close to it before either throwing a snowball or moving to a new spot.

2024-04-14 01:55 UTC, PBWiseman reviewed
The movement and pathfinding looks really good. I mentioned in our discussion on teams some ideas for implementing the player detection. The turning is still a little janky. Do we want sudden 8 way turning or smooth turning because currently there is both? And the smooth turning parts are sometimes slow enough that the target is reached and a new turn started before the first one is finished.

2024-04-14 01:59 UTC, ChaseBENNC9 commented
> The movement and pathfinding looks really good. I mentioned in our discussion on teams some ideas for implementing the player detection. The turning is still a little janky.

 Do we want sudden 8 way turning or smooth turning because currently there is both? And the smooth turning parts are sometimes slow enough that the target is reached and a new turn started before the first one is finished.
I think sudden turning and I am not sure why sometimes it rotates slowly. But I will work on that and start implementing the other ideas for player detection

2024-04-14 02:02 UTC, PBWiseman commented
> Do we want sudden 8 way turning or smooth turning because currently there is both? And the smooth turning parts are sometimes slow enough that the target is reached and a new turn started before the first one is finished. I think sudden turning and I am not sure why sometimes it rotates slowly. But I will work on that and start implementing the other ideas for player detection

There is some code in my branch for turning the player. I just set transform.forward to the movement direction. Might help?

2024-04-16 05:26 UTC, ChaseBENNC9 commented
The enemy should now only face in one of the 8 directions. at this point it is sudden turning and not smoothly rotating between each point. Player detection should also work in which it shows a blue line towards a player sphere if it is within range, and this is also with a slight buffer, so it doesn't have to always be exact.

2024-04-16 11:33 UTC, PBWiseman requested changes
Impressive work! The tracking and movement work really well. I assume the snowball throwing will be another else if state statement in the update? The only issue I can see at the moment is cleaning up the leftover debug statements and blocks of commented code that you aren't saving for later. Plus a few other nitpicks I left comments for on the lines of code

2024-04-16 11:33 UTC, PBWiseman commented on Assets/Scripts/EnemyMovement.cs
> +        {
There's an extra open and close bracket here, I assume from the commented else

2024-04-16 11:33 UTC, PBWiseman commented on Assets/Scripts/EnemyMovement.cs
> +        state = EnemyStates.Moving; //Sets the state to idle
The comment says idle state and the code says moving. I assume just an old comment?

2024-04-16 11:33 UTC, PBWiseman commented on Assets/Scripts/EnemyMovement.cs
> +    public GameObject sphere; //The sphere prefab
This doesn't seem to be used anymore, even for testing?

2024-04-17 05:59 UTC, ChaseBENNC9 commented
@PBWiseman All issues should be resolved

2024-04-17 06:21 UTC, PBWiseman requested changes
Everything looks good except for the fact that it seems to be trying to run at 600 fps? We may want to cap that. My computer is not happy with this
![16b02a82-321b-4bfc-bf31-2d51f86f9c52](https://github.com/TeamSnowballSlam/Snowball-Slam-World-Tour/assets/104882337/fcfb05c4-e278-43cd-a5a4-0808aa5d0f76)

2024-04-19 00:32 UTC, erokasyuart requested changes
Good commenting, nice seeing it all being explained, especially when getting lost in all those if statements!

One issue I have is this is all that happens in the scene?
![image](https://github.com/TeamSnowballSlam/Snowball-Slam-World-Tour/assets/100744555/f0d9b6a0-4295-4204-8157-9492e2fb0a71)

I checked and I'm up to date on the branch, have I just come in at the wrong time? The enemy doesn't move, just makes a line.

2024-04-28 20:06 UTC, PBWiseman approved these changes

2024-04-28 22:02 UTC, erokasyuart approved these changes

2024-04-28 22:06 UTC, merged